feat: add doc search to 404 page
neondatabase/website pull request #187
Opened 2022-09-22 13:43 UTC by vannyle

This pull request brings the docs search to the 404 page if the current URL of 404 page includes `/docs/`

2022-09-27 13:03 UTC, bolotskydev commented
LGTM, but I have problems with slow search bar appearing, let's switch from JS-based conditional rendering to CSS ? 🤔

2022-10-14 11:19 UTC, danieltprice commented on src/components/shared/search/input/input.jsx
> +        placeholder={isNotFoundPage ? 'Search from other pages' : 'Search'}
Should this be search *for* other pages?

2022-10-14 11:20 UTC, danieltprice commented on src/components/shared/search/input/input.jsx
> +        aria-label={isNotFoundPage ? 'Search from other pages' : 'Search'}
Should this be search for other pages?

2022-10-14 11:23 UTC, danieltprice requested changes
A couple of comments regarding "Search from" vs "Search for" in the Search box.

2022-10-14 11:26 UTC, vannyle commented on src/components/shared/search/input/input.jsx
> +        aria-label={isNotFoundPage ? 'Search from other pages' : 'Search'}
It makes sense, I'll make the change

2022-10-17 11:29 UTC, bolotskydev approved these changes

2022-10-17 11:30 UTC, bolotskydev commented
@danieltprice we are done with this, please, review one last time 🙏

2022-10-17 11:37 UTC, danieltprice approved these changes
LGTM! Thanks for the changes!

2022-10-17 12:59 UTC, merged