chore: update docs guide
neondatabase/website pull request #309
Opened 2022-11-11 17:13 UTC by vannyle

This pull request brings the update for the Documentation README, introducing new components for doc pages
- Admonition
- Code Tabs

2022-11-14 16:31 UTC, danieltprice approved these changes
LGTM. Thank you!

2022-11-15 08:18 UTC, bolotskydev commented on content/docs/README.md
> +```
```suggestion
```md
<Admonition type="note" title="Your title">
  The branch creation process does not increase load on the originating project. You can create a branch at any time without worrying about downtime or performance degradation.
</Admonition>

<Admonition type="info">
  The branch creation process does not increase load on the originating project. You can create a branch at any time without worrying about downtime or performance degradation.
</Admonition>
```
```

2022-11-15 08:21 UTC, bolotskydev commented on content/docs/README.md
> +In addition to emphasize your text, wrap text with `<Admonition></Admonition>` and set the proper type.
To improve the documentation readability, one can leverage an `Admonition` custom component. Just wrap your piece of text with `<Admonition></Admonition>` and pass the type.

2022-11-15 08:22 UTC, bolotskydev commented on content/docs/README.md
> +There are 5 types of Admonition: `note`, `important`, `tip`, `warning`, `info`.
```suggestion
There are 5 types of Admonition: `note`, `important`, `tip`, `warning`, `info`; the default is `note`.
```

2022-11-15 08:22 UTC, bolotskydev requested changes
Almost there! 💪

2022-11-15 09:49 UTC, vannyle commented
Thanks for the comments! @bolotskydev

2022-11-15 10:01 UTC, merged

2022-11-15 11:25 UTC, danieltprice reviewed
LGTM.