docs: update the units to make the unit dimensions right
neondatabase/website pull request #586
Opened 2023-03-15 22:37 UTC by stepashka

right now it looks like we divide by the amount of hours

2023-03-15 23:16 UTC, acervantes23 requested changes
@stepashka the units need to be separated by "-"

2023-03-16 09:17 UTC, danieltprice submitted a review, later dismissed

2023-03-16 09:33 UTC, acervantes23 requested changes

2023-03-16 09:33 UTC, acervantes23 commented on content/docs/introduction/billing.md
> +| AWS            | US West (Oregon)| Project storage | $0.000164 | GiBHour |
```suggestion
| AWS            | US West (Oregon)| Project storage | $0.000164 | GiB-hour |
```

2023-03-16 09:33 UTC, acervantes23 commented on content/docs/introduction/billing.md
> +| AWS            | Europe (Frankfurt)| Compute time| $0.11800 | ComputeHour |
```suggestion
| AWS            | Europe (Frankfurt)| Compute time| $0.11800 | Compute-hour |
```

2023-03-16 09:33 UTC, acervantes23 commented on content/docs/introduction/billing.md
> +| AWS            | Europe (Frankfurt)| Project storage  | $0.00018 | GiBHour |
```suggestion
| AWS            | Europe (Frankfurt)| Project storage  | $0.00018 | GiB-hour |
```

2023-03-16 09:33 UTC, acervantes23 commented on content/docs/introduction/billing.md
> +| AWS            | Asia Pacific (Singapore)| Compute time    | $0.12100 | ComputeHour |
```suggestion
| AWS            | Asia Pacific (Singapore)| Compute time    | $0.12100 | Compute-hour |
```

2023-03-16 09:33 UTC, acervantes23 commented on content/docs/introduction/billing.md
> +| AWS            | Asia Pacific (Singapore)  | Project storage    | $0.00018 | GiBHour |
```suggestion
| AWS            | Asia Pacific (Singapore)  | Project storage    | $0.00018 | GiB-hour |
```

2023-03-16 10:01 UTC, danieltprice commented on content/docs/introduction/billing.md
> +| AWS            | US East (Ohio)     | Compute time  | $0.10200 | ComputeHour |
fixed

2023-03-16 10:02 UTC, danieltprice approved these changes

2023-03-16 10:03 UTC, acervantes23 approved these changes

2023-03-16 10:04 UTC, merged