Add "Plans" item to the TOC
neondatabase/website pull request #815
Opened 2023-06-08 13:52 UTC by danieltprice

Add "Plans" item to the TOC.

2023-06-08 18:58 UTC, acervantes23 requested changes
@danieltprice  let's try and rephrase this sentence `The Neon Pro plan is a usage-based plan intended for small to medium teams or projects requiring more compute and storage than the [Neon Free Tier](https://neon-next-git-dprice-add-plans-items-to-toc-neondatabase.vercel.app/docs/introduction/technical-preview-free-tier) provides.`

Specifically, let's make sure we are communicating the free tier is for prototyping/ testing Neon's core functionality and that the Pro plan is meant for users who have finished their evaluation of Neon, had a positive experience and are now ready to properly start using the service either for serious development or running their production app.

Hopefully that is clear enough feedback (:

2023-06-09 10:59 UTC, acervantes23 approved these changes

2023-06-09 11:00 UTC, acervantes23 submitted a review, later dismissed

2023-06-09 11:34 UTC, danieltprice commented
> Hopefully that is clear enough feedback (:

Thanks @acervantes23 
Revised.

> Hopefully that is clear enough feedback (:

Thanks @acervantes23 
Please check out the revised version.

2023-06-10 11:31 UTC, danieltprice commented
Merged into a larger PR. https://github.com/neondatabase/website/pull/816

2023-06-10 11:31 UTC, closed without merging